### ISSUE TITLE
[Bug]: Class "App\Filament\Widgets\MailsPerStatusChart" not found

### ISSUE THREAD

**Issue by iAmKevinMcKee** [vormkracht10/filament-mails#3]
### What happened?

Tried to load the Events page for mails, and got this error

### How to reproduce the bug

Use the package and click here:
<img width="849" alt="image" src="https://github.com/user-attachments/assets/8fc12d92-75c4-4d69-af5b-3d3311289a00">

### Package Version

latest

### PHP Version

8.3

### Laravel Version

latest

**Comment by Baspa** [comment]
The widget was not implemented yet, removed the reference for now,.
