### ISSUE TITLE
[Bug]: Not installable with vormkracht10/laravel-mails 1.0

### ISSUE THREAD

**Issue by cord** [vormkracht10/filament-mails#4]
### What happened?

composer can not install 
- Root composer.json requires vormkracht10/filament-mails * -> satisfiable by vormkracht10/filament-mails[v1.0.0, v1.0.1].
- vormkracht10/filament-mails[v1.0.0, ..., v1.0.1] require vormkracht10/laravel-mails dev-main -> found vormkracht10/laravel-mails[dev-main] but it does not match your minimum-stability.

### How to reproduce the bug

run following commands

composer require vormkracht10/laravel-mails

composer require vormkracht10/filament-mails

### Package Version

1

### PHP Version

8.2

### Laravel Version

latest

### Notes

package version dependencies

**Comment by Baspa** [comment]
Should be fixed when you upgrade to the latest version now @cord

**Comment by cord** [comment]
thanks, works!

Very nice package, keep on the good work!
